{% set name = "macs2" %}
{% set version = "2.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ee9381bda61bacf65e2e31bde267cbcd61a1304457f8a00a0eb7632dd12419b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - numpy >=1.6
    - pip
    - pip
    - python
  run:
    - numpy >=1.6
    - python

test:
  imports:
    - MACS2
    - MACS2.IO

about:
  home: http://github.com/taoliu/MACS/
  license: BSD
  license_family: BSD
  license_file: 
  summary: Model Based Analysis for ChIP-Seq data
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
