{% set name = "nimnexus" %}
{% set version = "0.1.0" %}
{% set revision = "52aed74" %}
{% set sha256hash = "713a38bfcf8ce63f0f52dc06659d2123fc3acb8091d909e077c865c8d07e1685" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/avsecz/{{ name }}/archive/{{ revision }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 2
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pcre
    - htslib
  run:
    - pcre
    - htslib

test:
  commands:
    - nimnexus -h
    - nimnexus trim -h
    - nimnexus dedup -h
    
about:
  home: https://github.com/avsecz/nimnexus
  license: MIT
  summary: command-line tools for processing ChIP-nexus data
